defmodule GitHub.Repository.TemplateRepository do
  @moduledoc """
  Provides struct and type for a Repository.TemplateRepository
  """
  use GitHub.Encoder

  @type t :: %__MODULE__{
          __info__: map,
          allow_auto_merge: boolean | nil,
          allow_merge_commit: boolean | nil,
          allow_rebase_merge: boolean | nil,
          allow_squash_merge: boolean | nil,
          allow_update_branch: boolean | nil,
          archive_url: String.t() | nil,
          archived: boolean | nil,
          assignees_url: String.t() | nil,
          blobs_url: String.t() | nil,
          branches_url: String.t() | nil,
          clone_url: String.t() | nil,
          collaborators_url: String.t() | nil,
          comments_url: String.t() | nil,
          commits_url: String.t() | nil,
          compare_url: String.t() | nil,
          contents_url: String.t() | nil,
          contributors_url: String.t() | nil,
          created_at: String.t() | nil,
          default_branch: String.t() | nil,
          delete_branch_on_merge: boolean | nil,
          deployments_url: String.t() | nil,
          description: String.t() | nil,
          disabled: boolean | nil,
          downloads_url: String.t() | nil,
          events_url: String.t() | nil,
          fork: boolean | nil,
          forks_count: integer | nil,
          forks_url: String.t() | nil,
          full_name: String.t() | nil,
          git_commits_url: String.t() | nil,
          git_refs_url: String.t() | nil,
          git_tags_url: String.t() | nil,
          git_url: String.t() | nil,
          has_downloads: boolean | nil,
          has_issues: boolean | nil,
          has_pages: boolean | nil,
          has_projects: boolean | nil,
          has_wiki: boolean | nil,
          homepage: String.t() | nil,
          hooks_url: String.t() | nil,
          html_url: String.t() | nil,
          id: integer | nil,
          is_template: boolean | nil,
          issue_comment_url: String.t() | nil,
          issue_events_url: String.t() | nil,
          issues_url: String.t() | nil,
          keys_url: String.t() | nil,
          labels_url: String.t() | nil,
          language: String.t() | nil,
          languages_url: String.t() | nil,
          merge_commit_message: String.t() | nil,
          merge_commit_title: String.t() | nil,
          merges_url: String.t() | nil,
          milestones_url: String.t() | nil,
          mirror_url: String.t() | nil,
          name: String.t() | nil,
          network_count: integer | nil,
          node_id: String.t() | nil,
          notifications_url: String.t() | nil,
          open_issues_count: integer | nil,
          owner: GitHub.Repository.TemplateRepositoryOwner.t() | nil,
          permissions: GitHub.Repository.TemplateRepositoryPermissions.t() | nil,
          private: boolean | nil,
          pulls_url: String.t() | nil,
          pushed_at: String.t() | nil,
          releases_url: String.t() | nil,
          size: integer | nil,
          squash_merge_commit_message: String.t() | nil,
          squash_merge_commit_title: String.t() | nil,
          ssh_url: String.t() | nil,
          stargazers_count: integer | nil,
          stargazers_url: String.t() | nil,
          statuses_url: String.t() | nil,
          subscribers_count: integer | nil,
          subscribers_url: String.t() | nil,
          subscription_url: String.t() | nil,
          svn_url: String.t() | nil,
          tags_url: String.t() | nil,
          teams_url: String.t() | nil,
          temp_clone_token: String.t() | nil,
          topics: [String.t()] | nil,
          trees_url: String.t() | nil,
          updated_at: String.t() | nil,
          url: String.t() | nil,
          use_squash_pr_title_as_default: boolean | nil,
          visibility: String.t() | nil,
          watchers_count: integer | nil
        }

  defstruct [
    :__info__,
    :allow_auto_merge,
    :allow_merge_commit,
    :allow_rebase_merge,
    :allow_squash_merge,
    :allow_update_branch,
    :archive_url,
    :archived,
    :assignees_url,
    :blobs_url,
    :branches_url,
    :clone_url,
    :collaborators_url,
    :comments_url,
    :commits_url,
    :compare_url,
    :contents_url,
    :contributors_url,
    :created_at,
    :default_branch,
    :delete_branch_on_merge,
    :deployments_url,
    :description,
    :disabled,
    :downloads_url,
    :events_url,
    :fork,
    :forks_count,
    :forks_url,
    :full_name,
    :git_commits_url,
    :git_refs_url,
    :git_tags_url,
    :git_url,
    :has_downloads,
    :has_issues,
    :has_pages,
    :has_projects,
    :has_wiki,
    :homepage,
    :hooks_url,
    :html_url,
    :id,
    :is_template,
    :issue_comment_url,
    :issue_events_url,
    :issues_url,
    :keys_url,
    :labels_url,
    :language,
    :languages_url,
    :merge_commit_message,
    :merge_commit_title,
    :merges_url,
    :milestones_url,
    :mirror_url,
    :name,
    :network_count,
    :node_id,
    :notifications_url,
    :open_issues_count,
    :owner,
    :permissions,
    :private,
    :pulls_url,
    :pushed_at,
    :releases_url,
    :size,
    :squash_merge_commit_message,
    :squash_merge_commit_title,
    :ssh_url,
    :stargazers_count,
    :stargazers_url,
    :statuses_url,
    :subscribers_count,
    :subscribers_url,
    :subscription_url,
    :svn_url,
    :tags_url,
    :teams_url,
    :temp_clone_token,
    :topics,
    :trees_url,
    :updated_at,
    :url,
    :use_squash_pr_title_as_default,
    :visibility,
    :watchers_count
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      allow_auto_merge: :boolean,
      allow_merge_commit: :boolean,
      allow_rebase_merge: :boolean,
      allow_squash_merge: :boolean,
      allow_update_branch: :boolean,
      archive_url: {:string, :generic},
      archived: :boolean,
      assignees_url: {:string, :generic},
      blobs_url: {:string, :generic},
      branches_url: {:string, :generic},
      clone_url: {:string, :generic},
      collaborators_url: {:string, :generic},
      comments_url: {:string, :generic},
      commits_url: {:string, :generic},
      compare_url: {:string, :generic},
      contents_url: {:string, :generic},
      contributors_url: {:string, :generic},
      created_at: {:string, :generic},
      default_branch: {:string, :generic},
      delete_branch_on_merge: :boolean,
      deployments_url: {:string, :generic},
      description: {:string, :generic},
      disabled: :boolean,
      downloads_url: {:string, :generic},
      events_url: {:string, :generic},
      fork: :boolean,
      forks_count: :integer,
      forks_url: {:string, :generic},
      full_name: {:string, :generic},
      git_commits_url: {:string, :generic},
      git_refs_url: {:string, :generic},
      git_tags_url: {:string, :generic},
      git_url: {:string, :generic},
      has_downloads: :boolean,
      has_issues: :boolean,
      has_pages: :boolean,
      has_projects: :boolean,
      has_wiki: :boolean,
      homepage: {:string, :generic},
      hooks_url: {:string, :generic},
      html_url: {:string, :generic},
      id: :integer,
      is_template: :boolean,
      issue_comment_url: {:string, :generic},
      issue_events_url: {:string, :generic},
      issues_url: {:string, :generic},
      keys_url: {:string, :generic},
      labels_url: {:string, :generic},
      language: {:string, :generic},
      languages_url: {:string, :generic},
      merge_commit_message: {:enum, ["PR_BODY", "PR_TITLE", "BLANK"]},
      merge_commit_title: {:enum, ["PR_TITLE", "MERGE_MESSAGE"]},
      merges_url: {:string, :generic},
      milestones_url: {:string, :generic},
      mirror_url: {:string, :generic},
      name: {:string, :generic},
      network_count: :integer,
      node_id: {:string, :generic},
      notifications_url: {:string, :generic},
      open_issues_count: :integer,
      owner: {GitHub.Repository.TemplateRepositoryOwner, :t},
      permissions: {GitHub.Repository.TemplateRepositoryPermissions, :t},
      private: :boolean,
      pulls_url: {:string, :generic},
      pushed_at: {:string, :generic},
      releases_url: {:string, :generic},
      size: :integer,
      squash_merge_commit_message: {:enum, ["PR_BODY", "COMMIT_MESSAGES", "BLANK"]},
      squash_merge_commit_title: {:enum, ["PR_TITLE", "COMMIT_OR_PR_TITLE"]},
      ssh_url: {:string, :generic},
      stargazers_count: :integer,
      stargazers_url: {:string, :generic},
      statuses_url: {:string, :generic},
      subscribers_count: :integer,
      subscribers_url: {:string, :generic},
      subscription_url: {:string, :generic},
      svn_url: {:string, :generic},
      tags_url: {:string, :generic},
      teams_url: {:string, :generic},
      temp_clone_token: {:string, :generic},
      topics: [string: :generic],
      trees_url: {:string, :generic},
      updated_at: {:string, :generic},
      url: {:string, :generic},
      use_squash_pr_title_as_default: :boolean,
      visibility: {:string, :generic},
      watchers_count: :integer
    ]
  end
end
