name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish to Hex.pm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: "25.2"
          elixir-version: "1.14.2"

      - name: Publish Package
        run: |
          mix deps.get
          HEX_API_KEY=${{secrets.HEX_API_KEY}} mix hex.publish --yes --replace
